
variable "project_name" {
  description = "Name of the deployment"
  type        = string
  default     = "lumbenlengo-enterprise"
}

variable "region" {
  description = "AWS Region"
  type        = string
  default     = "us-east-1"
}

#Fix: You don’t need var.vpc_id here,
#Because the VPC ID is generated by the code, not chosen by you.