name: Deploy Production

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  id-token: write
  contents: read

env:
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
  TF_VAR_api_key: ${{ secrets.API_KEY }}
  TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
  IMAGE_TAG: ${{ github.ref_name }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build & Deploy to Production
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: "production-ready-app"
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.3"
          terraform_wrapper: false

      - name: Terraform Init
        # Points to the production backend configuration file
      
        run: terraform init -backend-config=environments/prod/backend.hcl

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        env:
          TF_VAR_image_tag: ${{ env.IMAGE_TAG }}
        run: |
          terraform plan \
            -no-color \
            -out=tfplan \
            -var-file="environments/prod/terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve tfplan